spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: qUdFBwSCWzPKBgYbUXFilvmkpqqzOZrf
    driver-class-name: org.postgresql.Driver

minio:
  endpoint: http://bucket.railway.internal:9000
  access-key: cZTpf66iOs7g47ONaFAHdKIEaFdmrXBz
  secret-key: bFUYS2BrSPip77iqvEs5gt03TcZhagz2ismohnOsExXY7EF1
  bucket: gift-images